ci: Explicitly control the container rebuilds
Right now we have a cronjob running that rebuilds the containers every
night (fsvo night, the earth is round after all). This causes us to pick
up any changes to the distribution across that rebuild boundary, so a
PR today may run in a different CI environment than the same PR
tomorrow.

Explicitly control this via a new CONTAINER_TAG environment variable
which specifies an opaque string to be used as tag.

This reshuffles the create_containers.yml workflow a bit:
- first we compose the container tag name for re-use by other steps
- log into the registry and check whether the tag exists already
- if it doesn't, rebuild as before and push it to our current repo.
  This is the user repo or the upstream repo after merge (or if the
  branch is on upstream). If it's a pull request skip the rebuild
  because we don't have permissions to push to the ghcr during a PR.

The last point matters: we now need to execute the create_containers.yml
workflow on push. This way a change to the containers means:
- change the tag
- push to user/<branchname> (or fwupd/<branchname> if pushed to origin)
- wait until the CI job for the push has finshed rebuilding
- file a PR which can now use that newly created container

But wait, there's more: because our containers now have a custom tag
and may be sitting in the user repo. So we need to know that tag and
repo in our downstream jobs. Each container creation job writes out a
simple JSON file that maps the distro to the container
URI, e.g.
   { "fedora-amd64": "ghcr.io/fwupd/fwupd/fedora-amd64:20260825.0" }
Those are merged together into a single JSON file that becomes the LUT
for the downstream job. We pass that LUT around as input to our jobs
and can look up our correct image per job.

Notably: the way how the lookup works means that a user needing to
rebuild the images can bump the contianer tag and have those container
be used in the PR. Then the containers get rebuilt once we push to main.

diff --git a/.github/workflows/create_containers.yml b/.github/workflows/create_containers.yml
--- a/.github/workflows/create_containers.yml
+++ b/.github/workflows/create_containers.yml
@@ -1,8 +1,19 @@
 name: Create containers
 on:
-  workflow_dispatch:
-  schedule:
-    - cron: "0 0 * * *"
+  push:
+    branches: ['**']
+    paths:
+      - '.github/workflows/create_containers.yml'
+  workflow_call:
+    outputs:
+      container_lut:
+        description: "A JSON lookup table for container URIs"
+        value: ${{ jobs.container_mapping.outputs.container_lut }}
+
+env:
+  # We currently have one tag for all containers, bumping it will rebuild
+  # them all.
+  CONTAINER_TAG: "2026-08-25.1"
 
 jobs:
   push_to_registry:
@@ -29,7 +40,52 @@ jobs:
         uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
         with:
           persist-credentials: false
+      - name: Assemble container tag
+        id: tag
+        env:
+          DISTRO: ${{ matrix.distros.DISTRO }}
+          ARCH: ${{ matrix.distros.ARCH }}
+          VARIANT: ${{ matrix.distros.VARIANT }}
+          CONTAINER_TAG: ${{ env.CONTAINER_TAG }}
+          USER_REPO: ${{ github.event.pull_request.head.repo.full_name }}
+        run: |
+          REPO="${USER_REPO:-$GITHUB_REPOSITORY}"
+          IDENTIFIER="${DISTRO}-${ARCH}${VARIANT:+-${VARIANT}}"
+          TAG="ghcr.io/${REPO}/fwupd-${IDENTIFIER}:${CONTAINER_TAG}"
+          echo "Using container tag ${TAG}"
+          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
+          echo "{\"$IDENTIFIER\": \"$TAG\"}" > "image_${IDENTIFIER}.json"
+      - name: Save the json files containing the container mappings
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+        with:
+          name: image-map-${{ strategy.job-index }}
+          path: image_*.json
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Check if the image already exists
+        id: check_container
+        run: |
+          TAG="${{steps.tag.outputs.tag}}"
+          if docker manifest inspect "${TAG}" > /dev/null 2>&1; then
+            echo "exists=true" >> "$GITHUB_OUTPUT"
+            echo "Container ${TAG} already exists."
+          else
+            echo "exists=false" >> "$GITHUB_OUTPUT"
+            echo "Container ${TAG} does not exist."
+          fi
+      - name: Let the user know
+        if: steps.check_container.outputs.exists != 'true' && github.event_name == 'pull_request'
+        run: |
+          TAG="${{steps.tag.outputs.tag}}"
+          echo "::error::The requested image ${TAG} does not yet exist. Wait until the push pipeline is complete, then re-run this job."
+          exit 1
+      # Steps below here are skipped for pull requests because we don't have permission anyway
       - name: Generate Dockerfile
+        if: steps.check_container.outputs.exists != 'true' && github.event_name != 'pull_request'
         run: >-
           ./contrib/ci/generate_docker.py
           --distro "${{ matrix.distros.DISTRO }}"
@@ -37,28 +93,29 @@ jobs:
           --arch "${{ matrix.distros.ARCH }}"
           ${{ matrix.distros.VARIANT && format('--variant "{0}"', matrix.distros.VARIANT) || '' }}
       - name: Set up Docker Buildx
+        if: steps.check_container.outputs.exists != 'true' && github.event_name != 'pull_request'
         uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Build container tag
-        id: tag
-        env:
-          DISTRO: ${{ matrix.distros.DISTRO }}
-          ARCH: ${{ matrix.distros.ARCH }}
-          VARIANT: ${{ matrix.distros.VARIANT }}
-        run: |
-          tag="ghcr.io/fwupd/fwupd/fwupd-${DISTRO}-${ARCH}"
-          if [ -n "${VARIANT}" ]; then
-            tag="${tag}-${VARIANT}"
-          fi
-          echo "tag=${tag}:latest" >> "$GITHUB_OUTPUT"
       - name: Push to GitHub Packages
+        if: steps.check_container.outputs.exists != 'true' && github.event_name != 'pull_request'
         uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
         with:
           context: .
           push: true
           tags: ${{ steps.tag.outputs.tag }}
+
+  container_mapping:
+    needs: push_to_registry
+    runs-on: ubuntu-latest
+    outputs:
+      container_lut: ${{ steps.merge.outputs.container_lut }}
+    steps:
+      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+        with:
+          pattern: image-map-*
+          merge-multiple: true
+      - name: merge individual JSON files into one
+        id: merge
+        run: |
+          jq -s 'add' image_*.json > container_lut.json
+          cat container_lut.json
+          echo "container_lut=$(jq -c . container_lut.json)" >> "$GITHUB_OUTPUT"
diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -4,6 +4,9 @@ on:
       publish:
         required: true
         type: boolean
+      container_lut:
+        required: true
+        type: string
 
 permissions:
   contents: read
@@ -39,6 +42,32 @@ jobs:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Find container image
+        id: find_container
+        env:
+          DISTRO: ${{ matrix.env.DISTRO }}
+          ARCH: ${{ matrix.env.ARCH }}
+          VARIANT: ${{ matrix.env.VARIANT }}
+          CONTAINER: ${{ matrix.env.CONTAINER }}
+          CONTAINER_LUT: ${{ inputs.container_lut }}
+        run: |
+          if [ -z "${CONTAINER}" ]; then
+            IDENTIFIER="${DISTRO}-${ARCH}${VARIANT:+-${VARIANT}}"
+          else
+            IDENTIFIER="${CONTAINER}"
+          fi
+          CONTAINER_URI=$(echo "$CONTAINER_LUT" | jq -r --arg key "$IDENTIFIER" '.[$key]')
+          if [ "${CONTAINER_URI}" = "null" ]; then
+            echo "$CONTAINER_LUT" | jq
+            echo "::error::Unable to find key '${IDENTIFIER}' in above container LUT"
+            exit 1
+          fi
+          echo "Using container ${CONTAINER_URI}"
+          if ! docker manifest inspect "${CONTAINER_URI}"; then
+            echo "::error::The requested image ${CONTAINER_URI} does not yet exist. Wait until the push pipeline is complete, then re-run this job."
+            exit 1
+          fi
+          echo "container_uri=${CONTAINER_URI}" >> "$GITHUB_OUTPUT"
       - name: Download tarball
         if: matrix.env.DISTRO == 'fedora' || matrix.env.DISTRO == 'centos'
         uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
@@ -49,6 +78,7 @@ jobs:
           CI_NETWORK: true
           VERSION: ${{ needs.library.outputs.version }}
           PYTHONWARNINGS: "ignore::DeprecationWarning:gi.events"
+          CONTAINER_URI: "${{ steps.find_container.outputs.container_uri }}"
         run: |
           docker run --privileged -t \
               -e "CI=$CI" \
@@ -57,7 +87,7 @@ jobs:
               -e "VERSION=$VERSION" \
               -e "PYTHONWARNINGS=$PYTHONWARNINGS" \
               -v "$GITHUB_WORKSPACE:/github/workspace" \
-              "ghcr.io/fwupd/fwupd/fwupd-${{ matrix.env.CONTAINER || join(matrix.env.*, '-') }}:latest" \
+              "${CONTAINER_URI}" \
               "./contrib/ci/$DISTRO${VARIANT:+-$VARIANT}.sh"
       - name: Save any applicable artifacts
         if: ${{ !cancelled() }}
@@ -81,6 +111,7 @@ jobs:
         env:
           CI_NETWORK: true
           PYTHONWARNINGS: "ignore::DeprecationWarning:gi.events"
+          CONTAINER_URI: "${{ steps.find_container.outputs.container_uri }}"
         run: |
           docker run --privileged -t \
               -e "CI=$CI" \
@@ -89,7 +120,7 @@ jobs:
               -e "VERSION=$VERSION" \
               -e "PYTHONWARNINGS=$PYTHONWARNINGS" \
               -v "$GITHUB_WORKSPACE:/github/workspace" \
-              "ghcr.io/fwupd/fwupd/fwupd-${{ matrix.env.CONTAINER || join(matrix.env.*, '-') }}:latest" \
+              "${CONTAINER_URI}" \
               "./contrib/ci/$DISTRO${VARIANT:+-$VARIANT}-test.sh"
       - name: Save any coverage data
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
